# Generated by Django 5.2 on 2025-05-01 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='image',
            field=models.ImageField(default='game_images/default.jpg', upload_to='game_images/'),
            preserve_default=False,
        ),
    ]
