# Generated by Django 5.2 on 2025-05-02 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_game_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.game'),
        ),
        migrations.AddField(
            model_name='order',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.game'),
        ),
    ]
