# Generated by Django 5.2 on 2025-05-09 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_useragreement'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Questions', models.CharField(max_length=300)),
                ('Answers', models.CharField(max_length=300)),
            ],
        ),
    ]
